name: Roasting with J.A.M.
favicon: null
layout_spectrum: 0.7695403986144811
typography_spectrum: 0.7816553451120853
title: Roasting With J.A.M.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#faceb1'
    - '#757575'
    - '#ababab'
  brandStrength: 0.24523363378830254
  lightness: 0.19608200923539698
  saturation: 0.9548893310129642
  rhythmicContrast: 0.5725265287328511
purpose: []
